import SwiftUI

struct MedicalReportView: View {
    var extractedText: String
    var fdaDetails: FDADrugDetail?
    var medicineName: String
    
    var body: some View {
        VStack(alignment: .leading, spacing: 20) {
            // Document Header
            HStack {
                Image(systemName: "cross.case.fill")
                    .font(.largeTitle)
                    .foregroundColor(.blue)
                Text("MediChain Health Report")
                    .font(.largeTitle)
                    .fontWeight(.heavy)
                Spacer()
            }
            
            Text("Generated on: \(Date().formatted(date: .long, time: .shortened))")
                .font(.subheadline)
                .foregroundColor(.gray)
            
            Divider()
            
            // Extracted Data Section
            Text("Extracted Prescription Data")
                .font(.title2)
                .fontWeight(.bold)
                .foregroundColor(.blue)
            
            Text(extractedText)
                .font(.system(.body, design: .monospaced))
                .padding()
                .background(Color(UIColor.systemGray6))
                .cornerRadius(8)
            
            // FDA Information Section
            if let fda = fdaDetails {
                Divider()
                
                Text("Official FDA Information: \(medicineName)")
                    .font(.title2)
                    .fontWeight(.bold)
                    .foregroundColor(.blue)
                
                if let dosage = fda.dosageAndAdministration?.first {
                    Text("Dosage & Administration:")
                        .font(.headline)
                    Text(dosage)
                        .font(.body)
                } else {
                    Text("No dosage information available.")
                        .font(.body)
                        .foregroundColor(.gray)
                }
            }
            
            Spacer()
            
            // Footer
            Divider()
            Text("Disclaimer: This report was generated by AI and should be reviewed by a certified medical professional.")
                .font(.caption)
                .foregroundColor(.gray)
                .multilineTextAlignment(.center)
                .frame(maxWidth: .infinity)
        }
        .padding(40)
        // A standard letter-size aspect ratio
        .frame(width: 612, height: 792)
        .background(Color.white)
    }
}
